Added variables.tf, outputs.tf, and updated source in main.tf
terraform-google-modules/terraform-google-cloud-router pull request #24
Opened 2021-03-31 19:39 UTC by betsy-lichtenberg

Added:
variables.tf
outputs.tf

Updated source in main.tf to remove the relative path

2021-04-05 20:59 UTC, morgante requested changes

2021-04-05 20:59 UTC, morgante commented on examples/nat/main.tf
> +  source = "terraform-google-modules/cloud-router/google"
Please add a version constraint.

2021-04-06 20:55 UTC, betsy-lichtenberg commented on examples/nat/main.tf
> +  source = "terraform-google-modules/cloud-router/google"
Done

2021-04-07 18:34 UTC, morgante approved these changes

2021-04-07 18:44 UTC, merged